# This file was generated by GoReleaser. DO NOT EDIT.
cask "axilio" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "d32ae7183755a486e6f8a63a87125beaf5fa21650ac4cbc57191d89dc45316b7"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8475353f980c5561a4b3439a2ffb0f2f56b3e334773610bcf65a485e89e8c4ef"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f3bb9634d47fa8b1a1d2f68e3c855a9d03d71ad53a67a631df377540d055860f"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2452fdb3f93992b144f318a525b2d9ee7fc66bb0b5b11f35bf2578981740c9b7"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "axilio"
  desc "Acquire and drive Axilio phones from the command line."
  homepage "https://axilio.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axilio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axilio"]
    end
  end

  # No zap stanza required

end
