# This file was generated by GoReleaser. DO NOT EDIT.
cask "axilio" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e252f54620375f6c2aa394ff6ffc295f7c40452276e276353808b876df04257a"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4aa368964be4cc3a2b9284978e12d1987deb768da7aa973534ed9156255cf4e4"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b40e885225ec84c9069bf3e4fd81a4570898b239166041e9b5192d14e97062c7"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "51ab2bba56b0318206ae755d800022a755a6f424e705de4be927da4163f0aa23"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "axilio"
  desc "Acquire and drive Axilio phones from the command line."
  homepage "https://axilio.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axilio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axilio"]
    end
  end

  # No zap stanza required

end
