# This file was generated by GoReleaser. DO NOT EDIT.
cask "axilio" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "99f36529e8a8ef479e3cc941d7d6effa0e7e0e9327bef1428bf873ccd6479b65"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e74576799d4b7fd607cf32eb16dafbfa35220f401f0c2c7b6b1568819a7bc7f"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8255944a08d964d4a769cca2daa48773bce8df2f0882d54afe3281415e593277"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dbfbd42ed47f85e8dafc59b692a31bdfd83ada3d9e219dcc10569a66bc78f22d"
      url "https://github.com/axilioai/cli/releases/download/v#{version}/axilio_#{version}_linux_arm64.tar.gz"
    end
  end

  name "axilio"
  desc "Acquire and drive Axilio phones from the command line."
  homepage "https://axilio.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axilio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/axilio"]
    end
  end

  # No zap stanza required

end
